openapi: 3.0.3
info:
  title: API Tienda 
  description: |-
    API para la gestión de los productos de una tienda. Se conecta con la API de almacén para obtener los datos.
    
    Algunos ejemplos de urls:
    - Productos de la tienda:
        http://{{server_tienda}}/api/productos
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/productos
tags:
  - name: productos
    description: Los productos de la tienda
paths:
  /productos:
    get:
      tags:
        - productos
      summary: Listar todos los productos de la tienda
      description: Muestra todos los productos de la tienda
      operationId: obtener_productos
      responses:
        '200':
          description: Operación correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/productos'          
    post:
      tags:
        - productos
      summary: Añade un nuevo producto
      description: Se añade un uevo producto a la tienda
      operationId: crear_producto
      requestBody:
        description: Crea un nuevo producto 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productos'
        required: true
      responses:
        '201':
          description: Operación correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productos'          
  /productos/{id}:
    get:
      tags:
        - productos
      summary: Obtener un producto por su id
      description: Devuelve un producto 
      operationId: obtener_producto
      parameters:
        - name: id
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productos'          
    put:
      tags:
        - productos
      summary: Actualizar el precio y el nombre de un producto de la tienda
      description: Actualizar producto por su id
      operationId: actualizar_producto
      requestBody:
        description: Modificar un producto de la tienda
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productos'
        required: true
      responses:
        '200':
          description: Operación correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productos'          
    delete:
      tags:
        - productos
      summary: Elimina un producto 
      description: Elimina un producto de la tienda
      operationId: eliminar_producto
      parameters:
        - name: id
          in: path
          description: Id del producto para eliminarlo
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Se ha borrado correctamente
  /productos/{id}/modificar-precio:
    put:
      tags:
        - productos
      summary: Modifica el precio de un producto
      description: ''
      operationId: modificar_precio
      parameters:
        - name: id
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Precio del producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productos-precio'
        required: true      
      responses:
        '200':
          description: Operación correcta
  /productos/{id}/obtener-almacen:
    get:
      tags:
        - productos
      summary: Obtiene las unidades del almacén 
      description: ''
      operationId: obtener_almacen
      parameters:
        - name: id
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        responses:
        '200':
          description: Se ha traido el producto correctamente
        '600':
          description: No se ha traido el producto porque no hay unidades disponibles
  /productos/{id}/vender:
    post:
      tags:
        - productos
      summary: Vende un producto de la tienda
      description: Si hay unidades disponibles en el almacén se vende el producto
      operationId: vender_producto
      parameters:
        - name: id
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Número de unidades que se quieren vender
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productos-cantidad'
        required: true      
      responses:
        '200':
          description: Se ha vendido el producto correctamente
        '600':
          description: No se ha vendido el producto porque no hay unidades disponibles
        '601':
          description: No se ha vendido el producto porque no tiene precio
components:
  schemas:
    productos:
      type: object
      properties:
        id:
          type: string
          example: Producto-1
        nombre:
          type: string
          example: Nombre del producto 1
        precio:
          type: integer
          format: int32
          example: 7
        unidades_vendidas:
          type: integer
          format: int32
          example: 4
    productos-precio:
      type: object
      properties:
        precio:
          type: integer
          format: int32
          example: 800
    productos-cantidad:
      type: object
      properties:
        cantidad:
          type: integer
          format: int32
          example: 7
